### PR TITLE
Revert "for joe"

### PR DESCRIPTION
**Pull request by respondicity**
Reverts RobotApocalypseCommittee/bekOS#1

### CODE REVIEW

**Comment by respondicity** [comment]
how dare u merge my pull request

**Comment by Jovascript** [comment]
I was planning on doing a clean-up anyway, so you've just helped the spring cleaning. Thanks!

**Comment by respondicity** [comment]
Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by respondicity** [comment]
Okay but don’t close my issue

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
